# Ejemplos

POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Eva", 
    "precio" : 20,
    "descripcion": "Mondongo"
}

### 

POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Eugenio", 
        "precio" : 20,
    "descripcion": "Mondongo" 
}

### 

GET http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/productos/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/productos/655a9b3e8b8747bc6a13a543 HTTP/1.1
content-type: application/json

{ 
    "nombre": "Pedro", 
        "precio" : 20,
    "descripcion": "Mondongo"
}

###

DELETE http://localhost:3000/api/productos/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

DELETE https://nxapi-mongodb.vercel.app/api/productos/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

### 

POST https://nxapi-mongodb.vercel.app/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jose", 
        "precio" : 20,
    "descripcion": "Mondongo" 
}

### 

DELETE https://nxapi-mongodb.vercel.app/api/productos/6542da35c20d9ad95c739702
content-type: application/json
